#:schema node_modules/wrangler/config-schema.json
name = "sublink-oookkjjbbvvcc"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "28c3509f5f4e49eebb1a5f4228478771" }
]

[assets]
directory = "./public"
